# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ChartsDemoCSV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChartsDemoCSV

# Pods for Charts
pod 'Charts'
pod 'CodableCSV', '~> 0.6.7'

end
